
spring:
  datasource:
    driver-classe-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/payments1?allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: mdymen_pass
  jpa:
    show-sql: true

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create

server:
  port: 8088
